version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: python3 main.py 5 10 1  # Replace 5, 10, and 1 with your desired values

workflows:
  build:
    jobs:
      - build
