version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python3 main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run tests
          command: python -m unittest discover

  deploy:
    working_directory: ~/circleci-python
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t myapp .
      - run:
          name: Deploy to container
          command: docker run -d --name myapp-container -p 8080:80 myapp

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
