version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
